name: Build Check

on:
  push:
    branches: ["main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

  final:
    if: always() && contains(join(needs.*.result, ','), 'success') && github.event_name == 'pull_request'
    needs: [build]
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Add Label "ci approved" to Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["ci approved"]
            })

      - name: Remove Label "ci rejected" from Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const labelsResponse = await github.rest.issues.listLabelsOnIssue({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const labels = labelsResponse.data; // Extract the label information from the response
            const hasRejectedLabel = labels.some(label => label.name === 'ci rejected');

            if (hasRejectedLabel) {
              await github.rest.issues.removeLabel({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: 'ci rejected'
              });
            }

  failure:
    if: failure() && github.event_name == 'pull_request'
    needs: [build]
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Add Label "ci rejected" to Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["ci rejected"]
            })
            - name: Remove Label "ci approved" from Pull Request

      - name: Remove Label "ci approved" from Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const labelsResponse = await github.rest.issues.listLabelsOnIssue({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const labels = labelsResponse.data; // Extract the label information from the response
            const hasApprovedLabel = labels.some(label => label.name === 'ci approved');

            if (hasApprovedLabel) {
              await github.rest.issues.removeLabel({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: 'ci approved'
              });
            }
