name: Node.js Package

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Build Package
        run: yarn build
        working-directory: ./dist

      - name: Publish to npm
        run: yarn publish
        working-directory: ./dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.YARN_TOKEN}}
